server:
  port: 8081
  mode: debug

database:
  host: localhost
  port: 3306
  username: root
  password: 111111aa
  dbname: base_admin_test

redis:
  host: localhost
  port: 6379
  password: ""
  db: 1

cors:
  allowed_origins:
    - http://test.example.com

log:
  level: info
  filename: ./logs/app.test.log