server:
  port: 8080

database:
  host: localhost
  port: 3306
  username: root
  password: 111111aa
  dbname: base_admin

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

cors:
  allowed_origins:
    - http://localhost:3000
    - http://localhost:8080

log:
  level: debug
  filename: ./logs/app.dev.log 